#!/bin/bash

source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script

YNH_VERSION	# Récupère le numéro de version de Yunohost.

CLEAN_SETUP () {
# Nettoyage des résidus d'installation non pris en charge par le script remove.
# Pas de nettoyage supplémentaire nécessaire ici...
	echo ""
}
TRAP_ON # Active trap pour arrêter le script si une erreur est détectée.

# Exit on command errors and treat unset variables as an error
set -eu

# Retrieve arguments
app=$YNH_APP_INSTANCE_NAME
domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
admin=$YNH_APP_ARG_ADMIN
password=$YNH_APP_ARG_PASSWORD
is_public=$YNH_APP_ARG_IS_PUBLIC
default_lang=$YNH_APP_ARG_DEFAULT_LANG

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Remove trailing slash
[ "$path" != "/" ] && path=${path%/}

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path}" -a "$app" \
    || ynh_die "Path not available: ${domain}${path}"

# Check the admin exists in YunoHost users
ynh_user_exists $admin

# Save app settings
ynh_app_setting_set "$app" admin "$admin"
ynh_app_setting_set "$app" is_public "$is_public"

# Create path for copying
src_path=/var/www/$app
sudo mkdir -p $src_path

# Retrieve sources and install them
version=$(cat ../conf/upstream_version)
wget -nc --quiet https://github.com/tontof/kriss_feed.git -P /tmp


# Set permissions
sudo chown -R root: $src_path
sudo chown -R www-data: $src_path/{data,plugins}
sudo find $src_path -type f -exec chmod 644 {} +
sudo find $src_path -type d -exec chmod 755 {} +

# Configure nginx settings
folder_path=${path%/}
sudo sed -i "s@YNH_EXAMPLE_PATH@$path@g" ../conf/nginx.conf
# If path is only / (without subfolder), add trailing slash to alias
alias_path=$src_path
nginx_conf="../conf/nginx.conf"
[ "$path" == '/' ] && alias_path=$alias_path'/'
sudo sed -i "s@YNH_EXAMPLE_ALIAS@$alias_path@g" $nginx_conf
sudo sed -i "s@YNH_EXAMPLE_FOLDER@$folder_path@g" $nginx_conf
sudo cp $nginx_conf /etc/nginx/conf.d/$domain.d/$app.conf

# Temporary set public accessible
ynh_app_setting_set "$app" unprotected_uris "/"

# Reload services
sudo service nginx reload
sudo yunohost app ssowatconf


