#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
is_public=$3

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a kriss
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Remove trailing "/" for next commands
if [[ ! "$path" == "/" ]]; then
    path=${path%/}
fi

# Copy files to the right place
final_path=/var/www/kriss
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
nginxconf=/etc/nginx/conf.d/$domain.d/zerobin.conf
sudo cp ../conf/nginx.conf $nginxconf
sudo chown root: $nginxconf
sudo chmod 600 $nginxconf

sudo yunohost app setting zerobin is_public -v "$is_public"
if [ "$is_public" = "Yes" ];
then
  sudo yunohost app setting zerobin unprotected_uris -v "/"
fi

sudo service nginx reload
sudo yunohost app ssowatconf
